spring:
  profiles:
    active: development
---
spring:
  profiles: development
  cloud:
    config:
      enabled: false
  data:
    mongodb:
      database: testdb
      host: mongo
      port: 27017
eureka:
  client:
    enabled: false
logging:
  level:
    ROOT: INFO
    org:
      springframework:
        web: DEBUG
        data.mongodb: DEBUG
