spring:
  profiles:
    active: development
---
spring:
  data:
    mongodb:
      database: testdb
      host: mongo
      port: 27017
  cloud.config.discovery.enabled: false
eureka:
  client:
    enabled: false
logging:
  level:
    ROOT: INFO
    org:
      springframework:
        web: DEBUG
        data.mongodb: DEBUG
