spring:
  profiles:
    active: development

---
spring:
  profiles: production
  data:
    mongodb:
      database: productiondb
      host: mongo
      port: 27017
logging:
  level: info

---
spring:
  profiles: development
  data:
    mongodb:
      database: testdb
      host: mongo
      port: 27017
logging:
  level:
    ROOT: INFO
    org:
      springframework:
        web: DEBUG
        data.mongodb: DEBUG
