# embedded server configuration
server:
      port: 8080
# Customize application info information
info:
    app:
       name: ${name}
       description: ${description}
       version: ${version}
       realm: development

# enable shutdown of application via a POST request.
endpoints:
         shutdown:
                 enabled: true
         health:
               sensitive: false    # display full details for non-authenticated requests

spring:
       # show the banner file during startup
       main:
            show_banner: true
       # mongodb datasource configuration
       data:
            mongodb:
                    host: mongodb
                    port: 27017
                    database: restdb
       # json configuration
       jackson:
               serialization:
                   indent_output: true

# which logback configuration file to use
logging:
      config: classpath:logback.xml

##### e Profile specific overrides #####

# integration testing
---
spring:
      profiles: integration
info:
    app:
       realm: integration-test

# live
---
spring:
      profiles: live
info:
    app:
       realm: production