# Customize application info information
info:
    app:
       name: ${name}
       description: ${description}
       version: ${version}
       realm: development

spring:
      main:
          show_banner: false

# spring batch config (BatchDatabaseInitializer)
      batch:
            job:
                names: job1,job2
                enabled: false   # here we disbaled default spring boot jobs launcher, see JobLauncherCommandLineRunner
            initializer:
                        enabled: false # here we disbaled default spring boot jobs launcher, see JobLauncherCommandLineRunner
            schema: # batch schema to load

# logging config
logging:
       config: classpath:logback.xml

# enable shutdown of application via a POST
endpoints:
          shutdown:
                   enabled: true
          health:
                 sensitive: false    # display full details for non-authenticated requests

# cutomizing management endpoints
management:
          context-path: /manage

##### e Profile specific overrides #####

# integration testing
---
spring:
      profiles: integration
info:
    app:
       realm: integration-test

# live
---
spring:
      profiles: live
info:
    app:
       realm: production